-- AlterTable
ALTER TABLE "tokens" ADD COLUMN     "liquidity" DECIMAL(38,18) NOT NULL DEFAULT 0,
ADD COLUMN     "logo_url" TEXT,
ADD COLUMN     "market_cap" DECIMAL(38,18) NOT NULL DEFAULT 0,
ADD COLUMN     "price" DECIMAL(38,18) NOT NULL DEFAULT 0,
ADD COLUMN     "volume_24h" DECIMAL(38,18) NOT NULL DEFAULT 0;
